### ISSUE TITLE
Woul you please port it to 1.18.2?

### ISSUE THREAD

**Issue by ardissaps** [vsadge/extended-recipes#1]
Thank you very much!

**Comment by vsadge** [comment]
Of course 😊!

**Comment by vsadge** [comment]
Fabric 1.18 and higher is now supported on the latest release. Download here: [Modrinth](https://modrinth.com/mod/extended-recipes) 😊

**Comment by ardissaps** [comment]
> Fabric 1.18 and higher is now supported on the latest release. Download here: [Modrinth](https://modrinth.com/mod/extended-recipes) 😊

Thank you very much! :)
